-- BookVerse PostgreSQL Schema
-- Approved ERD: 17 entities
-- Branch: tabassum-work

BEGIN;

-- 1. roles
CREATE TABLE roles (
    role_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   varchar(30)  NOT NULL,
    description varchar(255),

    CONSTRAINT uq_roles_role_name UNIQUE (role_name),
    CONSTRAINT chk_roles_role_name_not_empty CHECK (length(trim(role_name)) > 0)
);

-- 2. users
CREATE TABLE users (
    user_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id         integer      NOT NULL,
    full_name       varchar(100) NOT NULL,
    username        varchar(50)  NOT NULL,
    email           varchar(100) NOT NULL,
    password_hash   varchar(255) NOT NULL,
    phone           varchar(20),
    is_active       boolean      NOT NULL DEFAULT true,
    created_on      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_users_role_id
        FOREIGN KEY (role_id) REFERENCES roles (role_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_full_name_not_empty CHECK (length(trim(full_name)) > 0),
    CONSTRAINT chk_users_username_not_empty CHECK (length(trim(username)) > 0),
    CONSTRAINT chk_users_email_not_empty CHECK (length(trim(email)) > 0)
);

-- 3. publishers
CREATE TABLE publishers (
    publisher_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_name  varchar(100) NOT NULL,
    country         varchar(50),
    website         varchar(255),
    created_on      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_publishers_publisher_name_not_empty CHECK (length(trim(publisher_name)) > 0)
);

-- 4. authors
CREATE TABLE authors (
    author_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_name     varchar(100) NOT NULL,
    nationality     varchar(50),
    biography       text,
    created_on      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_authors_author_name_not_empty CHECK (length(trim(author_name)) > 0)
);

-- 5. genres
CREATE TABLE genres (
    genre_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name      varchar(50) NOT NULL,
    description     varchar(255),
    created_on      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_genres_genre_name_not_empty CHECK (length(trim(genre_name)) > 0)
);

-- 6. books
CREATE TABLE books (
    book_id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_id     integer      NOT NULL,
    isbn             varchar(20)  NOT NULL,
    title            varchar(200) NOT NULL,
    description      text,
    language         varchar(30),
    edition          varchar(30),
    publication_year integer,
    total_pages      integer,
    cover_image      varchar(255),
    created_on       timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_on  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP   ,

    CONSTRAINT fk_books_publisher_id
        FOREIGN KEY (publisher_id) REFERENCES publishers (publisher_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_books_isbn UNIQUE (isbn),
    CONSTRAINT chk_books_isbn_not_empty CHECK (length(trim(isbn)) > 0),
    CONSTRAINT chk_books_title_not_empty CHECK (length(trim(title)) > 0),
CONSTRAINT chk_books_publication_year_reasonable
    CHECK (
        publication_year IS NULL
        OR publication_year BETWEEN 1000 AND 2100
    ),
CONSTRAINT chk_books_total_pages_positive
    CHECK (total_pages IS NULL OR total_pages > 0)
);

-- 7. book_authors
CREATE TABLE book_authors (
    book_id      integer NOT NULL,
    author_id    integer NOT NULL,
    author_order integer NOT NULL,

    PRIMARY KEY (book_id, author_id),
    CONSTRAINT fk_book_authors_book_id
        FOREIGN KEY (book_id) REFERENCES books (book_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_book_authors_author_id
        FOREIGN KEY (author_id) REFERENCES authors (author_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_book_authors_author_order_positive CHECK (author_order > 0)
);

-- 8. book_genres
CREATE TABLE book_genres (
    book_id  integer NOT NULL,
    genre_id integer NOT NULL,

    PRIMARY KEY (book_id, genre_id),
    CONSTRAINT fk_book_genres_book_id
        FOREIGN KEY (book_id) REFERENCES books (book_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_book_genres_genre_id
        FOREIGN KEY (genre_id) REFERENCES genres (genre_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- 9. book_copies
CREATE TABLE book_copies (
    copy_id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id           integer     NOT NULL,
    barcode           varchar(50) NOT NULL,
    status            varchar(20) NOT NULL DEFAULT 'available',
    condition         varchar(20),
    shelf_location    varchar(30),
    acquisition_date  date,
    created_on        timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_on   timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_book_copies_book_id
        FOREIGN KEY (book_id) REFERENCES books (book_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_book_copies_barcode UNIQUE (barcode),
    CONSTRAINT chk_book_copies_barcode_not_empty CHECK (length(trim(barcode)) > 0)
    CONSTRAINT chk_book_copies_barcode_not_empty
    CHECK (length(trim(barcode)) > 0),

CONSTRAINT chk_book_copies_status
    CHECK (
        status IN (
            'available',
            'borrowed',
            'reserved',
            'lost',
            'damaged',
            'inactive'
        )
    )
);

-- 10. borrows
CREATE TABLE borrows (
    borrow_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer NOT NULL,
    copy_id         integer NOT NULL,
    borrow_date     date      NOT NULL,
    due_date        date      NOT NULL,
    return_date     date,
    renew_count     integer   NOT NULL DEFAULT 0,
    created_on      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_borrows_user_id
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_borrows_copy_id
        FOREIGN KEY (copy_id) REFERENCES book_copies (copy_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_borrows_renew_count_non_negative
    CHECK (renew_count >= 0),

CONSTRAINT chk_borrows_due_date_valid
    CHECK (due_date >= borrow_date),

CONSTRAINT chk_borrows_return_date_valid
    CHECK (
        return_date IS NULL
        OR return_date >= borrow_date
    )
);

-- 11. reservations
CREATE TABLE reservations (
    reservation_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          integer     NOT NULL,
    book_id          integer     NOT NULL,
    reservation_date date        NOT NULL DEFAULT CURRENT_DATE,
queue_position   integer     NOT NULL,
status           varchar(20) NOT NULL DEFAULT 'active',
    created_on       timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_on  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_reservations_user_id
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_reservations_book_id
        FOREIGN KEY (book_id) REFERENCES books (book_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_reservations_queue_position_positive
    CHECK (queue_position > 0),

CONSTRAINT chk_reservations_status
    CHECK (
        status IN (
            'active',
            'fulfilled',
            'cancelled',
            'expired'
        )
    )
);

-- 12. fines
CREATE TABLE fines (
    fine_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrow_id       integer        NOT NULL UNIQUE,
    amount          numeric(10, 2) NOT NULL,
    reason          varchar(100)   NOT NULL,
    payment_date    date,
    created_on      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_fines_borrow_id
        FOREIGN KEY (borrow_id) REFERENCES borrows (borrow_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_fines_amount_non_negative CHECK (amount >= 0),
    CONSTRAINT chk_fines_reason_not_empty CHECK (length(trim(reason)) > 0)
);

-- 13. reviews
CREATE TABLE reviews (
    review_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer NOT NULL,
    book_id         integer NOT NULL,
    rating          integer NOT NULL,
    review_text     text,
    created_on      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_reviews_user_id
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_reviews_book_id
        FOREIGN KEY (book_id) REFERENCES books (book_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_reviews_rating_range CHECK (rating BETWEEN 1 AND 5)
);

-- 14. bookshelves
CREATE TABLE bookshelves (
    shelf_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer      NOT NULL,
    shelf_name      varchar(100) NOT NULL,
    description     varchar(255),
    visibility      varchar(20)  NOT NULL DEFAULT 'private',
    created_on      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_bookshelves_user_id
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_bookshelves_shelf_name_not_empty
    CHECK (length(trim(shelf_name)) > 0),

CONSTRAINT chk_bookshelves_visibility
    CHECK (visibility IN ('private', 'public'))
);

-- 15. bookshelf_items
CREATE TABLE bookshelf_items (
    shelf_id   integer NOT NULL,
    book_id    integer NOT NULL,
    added_date date NOT NULL DEFAULT CURRENT_DATE,

    PRIMARY KEY (shelf_id, book_id),
    CONSTRAINT fk_bookshelf_items_shelf_id
        FOREIGN KEY (shelf_id) REFERENCES bookshelves (shelf_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_bookshelf_items_book_id
        FOREIGN KEY (book_id) REFERENCES books (book_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- 16. audit_logs
CREATE TABLE audit_logs (
    log_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer      ,
    action      varchar(100) NOT NULL,
    table_name  varchar(50)  NOT NULL,
    record_id   integer      NOT NULL,
    action_time timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_logs_user_id
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_audit_logs_action_not_empty CHECK (length(trim(action)) > 0),
    CONSTRAINT chk_audit_logs_table_name_not_empty CHECK (length(trim(table_name)) > 0)
);

-- 17. procedure_call_logs
CREATE TABLE procedure_call_logs (
    call_log_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer      ,
    procedure_name  varchar(100) NOT NULL,
    execution_time  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status          varchar(30)  NOT NULL,

    CONSTRAINT fk_procedure_call_logs_user_id
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_procedure_call_logs_procedure_name_not_empty
    CHECK (length(trim(procedure_name)) > 0),

CONSTRAINT chk_procedure_call_logs_status
    CHECK (status IN ('success', 'failed'))
);

COMMIT;
