BEGIN;

CREATE TABLE borrowing_requests (
    request_id integer GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    user_id integer NOT NULL
        REFERENCES users(user_id) ON DELETE RESTRICT,

    book_id integer NOT NULL
        REFERENCES books(book_id) ON DELETE RESTRICT,

    borrow_id integer
        REFERENCES borrows(borrow_id) ON DELETE RESTRICT,

    request_type varchar(10) NOT NULL
        CHECK (request_type IN ('borrow', 'return', 'renew')),

    status varchar(10) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'approved', 'declined')),

    requested_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

    reviewed_by integer
        REFERENCES users(user_id) ON DELETE RESTRICT,

    reviewed_on timestamp,

    decision_reason varchar(500),

    -- Return and renewal requests must reference an existing loan.
    -- Borrow requests receive their loan ID when approved.
    CONSTRAINT chk_request_borrow_link CHECK (
        (
            request_type = 'borrow'
            AND (
                (status = 'approved' AND borrow_id IS NOT NULL)
                OR
                (status IN ('pending', 'declined') AND borrow_id IS NULL)
            )
        )
        OR
        (
            request_type IN ('return', 'renew')
            AND borrow_id IS NOT NULL
        )
    ),

    -- A decision must identify its reviewer and time.
    CONSTRAINT chk_request_review CHECK (
        (
            status = 'pending'
            AND reviewed_by IS NULL
            AND reviewed_on IS NULL
            AND decision_reason IS NULL
        )
        OR
        (
            status IN ('approved', 'declined')
            AND reviewed_by IS NOT NULL
            AND reviewed_on IS NOT NULL
        )
    ),

    CONSTRAINT chk_request_review_time CHECK (
        reviewed_on IS NULL OR reviewed_on >= requested_on
    )
);

-- One pending borrow request per student per book.
CREATE UNIQUE INDEX uq_pending_borrow_request
ON borrowing_requests (user_id, book_id)
WHERE request_type = 'borrow' AND status = 'pending';

-- Prevent simultaneous pending return/renewal requests for one loan.
CREATE UNIQUE INDEX uq_pending_loan_request
ON borrowing_requests (borrow_id)
WHERE request_type IN ('return', 'renew') AND status = 'pending';

-- Student request history.
CREATE INDEX idx_borrowing_requests_user
ON borrowing_requests (user_id, requested_on DESC);

-- Librarian review queue.
CREATE INDEX idx_borrowing_requests_pending
ON borrowing_requests (requested_on, request_id)
WHERE status = 'pending';

COMMIT;