BEGIN;

CREATE TABLE librarian_applications (
    application_id integer GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    user_id integer NOT NULL
        REFERENCES users(user_id) ON DELETE RESTRICT,

    status varchar(10) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'approved', 'declined')),

    requested_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

    reviewed_by integer
        REFERENCES users(user_id) ON DELETE RESTRICT,

    reviewed_on timestamp,

    decision_reason varchar(500),

    CONSTRAINT chk_librarian_application_review CHECK (
        (
            status = 'pending'
            AND reviewed_by IS NULL
            AND reviewed_on IS NULL
            AND decision_reason IS NULL
        )
        OR
        (
            status IN ('approved', 'declined')
            AND reviewed_by IS NOT NULL
            AND reviewed_on IS NOT NULL
        )
    ),

    CONSTRAINT chk_librarian_application_review_time CHECK (
        reviewed_on IS NULL OR reviewed_on >= requested_on
    ),

    CONSTRAINT chk_librarian_application_reviewer CHECK (
        reviewed_by IS NULL OR reviewed_by <> user_id
    )
);

-- Prevent multiple pending applications from the same account.
CREATE UNIQUE INDEX uq_pending_librarian_application
ON librarian_applications (user_id)
WHERE status = 'pending';

-- Support the admin's pending application list.
CREATE INDEX idx_librarian_applications_pending
ON librarian_applications (requested_on, application_id)
WHERE status = 'pending';

-- Support viewing an account's application history.
CREATE INDEX idx_librarian_applications_user
ON librarian_applications (user_id, requested_on DESC);

COMMIT;